services:
    llm-manager:
        container_name: llm-manager
        build:
            context: ./llm-manager
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        env_file:
            - .env
        depends_on:
            - llm-core

    llm-core:
        container_name: llm-core
        build:
            context: ./llm-core
            dockerfile: Dockerfile
        ports:
            - 11435:11434
        env_file:
            - .env

    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - 80:80
        env_file:
            - .env
        depends_on:
            - llm-manager
            - llm-core

    api-gateway:
        container_name: api-gateway
        build:
            context: ./api-gateway
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        env_file:
            - .env
        depends_on:
            - llm-manager
            - llm-core
