services:
  llm-manager:
    container_name: llm-manager
    build:
      context: ./llm-manager
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./llm-manager/.env.production
    depends_on:
      - llm-core

  llm-core:
    container_name: llm-core
    build:
      context: ./llm-core
      dockerfile: Dockerfile
    ports:
      - 11435:11434
