name: Build and Push Docker Compose Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
a
      - name: Tag and Push llm-manager
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/projects:llm-manager-latest ./llm-manager
          docker push ${{ secrets.DOCKER_USERNAME }}/projects:llm-manager-latest

      - name: Tag and Push llm-core
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/projects:llm-core-latest ./llm-core
          docker push ${{ secrets.DOCKER_USERNAME }}/projects:llm-core-latest
